version: "3.8"

services:
  app:
    container_name: careerdive_front
    build:
      context: ../
      dockerfile: ./Dockerfile # context 경로 기준 상대경로
      target: builder
    volumes:
      # docker-comose 파일 경로 기준 상대 경로
      - ../:/root/src
    env_file:
      - ../src/.env
    ports:
      - 3333:3333
    stdin_open: true # docker run -i
    tty: true # docker run -t
    entrypoint: /bin/sh
