apiVersion: v1
kind: Pod
metadata:
  name: kaniko-cd-front
  namespace: jenkins
spec:
  containers:
  - name: kaniko-cd-front
    image: gcr.io/kaniko-project/executor:latest
    imagePullPolicy: Always
    args:
    - "--dockerfile=Dockerfile"
    - "--context=git://github.com/steinjun0/career-dive-react.git"
    - "--destination=516218207558.dkr.ecr.ap-northeast-2.amazonaws.com/career-dive-react:latest"
    - "--cache=true"
    envFrom:
    - secretRef:
        name: kaniko-secret
  restartPolicy: Never
  nodeName: bdg-msi
  volumes:
  - name: docker-config
    configMap:
      name: docker-config
